  post_build:
    commands:
      - echo "==== out/ フォルダ確認 ===="
      - ls -la out/

      - echo "==== HTMLファイル構成を調整 ===="
      - |
        for file in out/*.html; do
          name=$(basename "$file" .html)
          if [ "$name" != "index" ] && [ "$name" != "404" ]; then
            mkdir -p "out/$name"
            mv "$file" "out/$name/index.html"
            # 元の menu.html を削除（mv で移動済みでも path は有効）
            rm -f "out/${name}.html"
          fi
        done

      - echo "==== 最終的な out/ の構成 ===="
      - find out/ -type f

      - echo "==== S3バケットの中身確認（一覧）===="
      - aws s3 ls s3://izumi2-backet/

      - echo "==== S3へアップロード ===="
      - aws s3 cp out/ s3://izumi2-backet/out/ --recursive
