version: 0.2

phases:
  install:
    commands:
      - npm ci

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo "==== ファイル整理 ===="
      - |
        for file in out/*.html; do
          name=$(basename "$file" .html)
          if [ "$name" != "index" ] && [ "$name" != "404" ]; then
            mkdir -p "out/$name"
            mv "$file" "out/$name/index.html"
            [ -f "out/${name}.txt" ] && mv "out/${name}.txt" "out/$name/index.txt"
          fi
        done

artifacts:
  files:
    - '**/*'
  base-directory: out
