version: 0.2

phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo "==== out/ フォルダ確認 ===="
      - ls -la out/
      - echo "==== S3バケットの中身確認（一覧）===="
      - aws s3 ls s3://izumi2-backet/
      - echo "==== S3へアップロード ===="
      - aws s3 cp out/ s3://izumi2-backet/ --recursive
