version: 0.2

phases:
  install:
    commands:
      - npm ci

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo "==== out/ フォルダ確認 ===="
      - ls -la out/
      
      # HTMLファイルを /xxx/index.html に移動（index.html, 404.html を除く）
      - echo "==== HTMLファイル構成を調整 ===="
      - |
        for file in out/*.html; do
          name=$(basename "$file" .html)
          if [ "$name" != "index" ] && [ "$name" != "404" ]; then
            mkdir -p "out/$name"
            mv "$file" "out/$name/index.html"
          fi
        done

        find out/ -maxdepth 1 -type f -name '*.html' ! -name 'index.html' ! -name '404.html' -exec rm {} \;

      - echo "==== S3バケットの中身確認（一覧）===="
      - aws s3 ls s3://izumi2-backet/

      - echo "==== S3へアップロード ===="
      - aws s3 cp out/ s3://izumi2-backet/out/ --recursive
